In [1]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
np.array([1,7,2,17])

array([ 1,  7,  2, 17])

In [3]:
np.ones?

In [4]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [9]:
print(np.arange(8))
print(np.arange(1,8))
print(np.arange(1,15,3))
print(np.arange(15,2,-3))

[0 1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[ 1  4  7 10 13]
[15 12  9  6  3]
